#!/usr/bin/bash

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

if [[ "$BRANCH_NAME" != "main" && "$BRANCH_NAME" != "develop" && "$BRANCH_NAME" != "release/"* ]]; then
    exit 0
fi

run_gradle_task() {
    local task_name=$1
    echo "Running Gradle '$task_name' task on branch: $BRANCH_NAME..."
    ./gradlew "$task_name"

    if [ $? -ne 0 ]; then
        echo -e "\033[31m"
        echo -e "-------------------------------------------------------------"
        echo -e "COMMIT ABORTED. Please solve reported issues before retrying."
        echo -e "-------------------------------------------------------------\033[0m"
        exit 1
    fi
}

run_gradle_task "check"
run_gradle_task "jacocoTestCoverageVerification"

exit 0
