import com.github.spotbugs.snom.SpotBugsTask

plugins {
    application
    alias(libs.plugins.gradlejavaqa)
    alias(libs.plugins.javafxplugin)
}

repositories {
    mavenCentral()
}


java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

javafx {
    version = "21"
    modules("javafx.controls", "javafx.controls", "javafx.fxml", "javafx.swing", "javafx.graphics")
}

val mockitoAgent = configurations.create("mockitoAgent")

dependencies {
    implementation(libs.spotbugs.annotations)

    implementation(libs.commons.lang3)

    // Dependency injection
    implementation(libs.avaje.inject)
    implementation(libs.avaje.spi.service)
    annotationProcessor(libs.avaje.inject.generator)

    // Logging
    implementation(libs.slf4j.api)
    runtimeOnly(libs.logback.classic)

    // Validation
    implementation(libs.jakarta.validation.api)
    implementation(libs.hibernate.validator)
    implementation(libs.jakarta.el)

    // JPA and Database
    implementation(libs.jakarta.persistence.api)
    implementation(libs.hibernate.core)
    runtimeOnly(libs.h2.database)

    // JavaFX dependencies
    implementation("io.github.makbn:jlmap-fx:2.0.0")

    // Test dependencies
    testImplementation(libs.junit.jupiter)
    testImplementation(libs.junit.platform.launcher)
    testImplementation(libs.mockito.core)
    mockitoAgent(libs.mockito.core) { isTransitive = false }
    testImplementation(libs.mockito.junit)

    // JavaFX test dependencies
    testImplementation(libs.testfx)
    testImplementation(libs.testfx.junit5)
    testImplementation(libs.hamcrest)
    testImplementation(libs.testfx.openjfx.monocle)
}


//
// Tests configuration
//

val showNodeTestsTag = "showNodeTest"

tasks.named<Test>("test") {
    useJUnitPlatform {
        excludeTags(showNodeTestsTag)
    }

    // TestFX headless-mode configuration
    @Suppress("UNNECESSARY_NOT_NULL_ASSERTION")
    jvmArgs = jvmArgs!!.toMutableList().apply {
        add("-Djava.awt.headless=true")
        add("-Dtestfx.robot=glass")
        add("-Dtestfx.headless=true")
        add("-Dprism.order=sw")
    }

    // Test database config
    systemProperties["db.driver"] = "org.h2.Driver"
    systemProperties["db.url"] = "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL"
    systemProperties["db.user"] = "sa"
    systemProperties["db.password"] = ""
    systemProperties["db.schema-action"] = "drop-and-create"
}

tasks.register<Test>("runShowNodeTest") {
    testClassesDirs = sourceSets["test"].output.classesDirs
    classpath = sourceSets["test"].runtimeClasspath

    useJUnitPlatform {
        includeTags(showNodeTestsTag)
    }

    // Test database config
    systemProperties["db.driver"] = "org.h2.Driver"
    systemProperties["db.url"] = "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL"
    systemProperties["db.user"] = "sa"
    systemProperties["db.password"] = ""
    systemProperties["db.schema-action"] = "drop-and-create"
}

//
// SpotBugs settings
//

tasks.withType<SpotBugsTask>().configureEach {
    dependsOn(tasks.named("compileJava"))
    dependsOn(tasks.named("compileTestJava"))

    classDirs.setFrom(
        classDirs.map { dir ->
            if (dir.isDirectory) {
                fileTree(dir) {
                    // Exclude classes generated by Avaje inject
                    exclude("**/*\$DI.class")
                }
            } else {
                dir
            }
        }
    )
}

//
// JaCoCo (code coverage) settings
//

tasks.jacocoTestCoverageVerification {
    violationRules {
        rule {
            limit {
                minimum = "0.7".toBigDecimal()
            }
        }
    }
}

//
// Check task configuration
//

tasks.check {
    dependsOn(tasks.checkstyleMain)
    dependsOn(tasks.checkstyleTest)
    dependsOn(tasks.pmdMain)
    dependsOn(tasks.pmdTest)
    dependsOn(tasks.spotbugsMain)
    dependsOn(tasks.spotbugsTest)
    finalizedBy(tasks.jacocoTestCoverageVerification)
    finalizedBy(tasks.jacocoTestReport)
}